
import { Game, HeroGame, NavItem } from "./types";

export const NAV_ITEMS: NavItem[] = [
  { icon: "grid_view", label: "Store Front", isActive: true },
  { icon: "calculate", label: "Mathematics" },
  { icon: "science", label: "Science" },
  { icon: "menu_book", label: "Language" },
  { icon: "public", label: "Social Studies" },
  { icon: "monitor_heart", label: "Health & PE" },
  { icon: "self_improvement", label: "Wellness" },
  { icon: "casino", label: "Decision" },
  { icon: "groups", label: "Group Activities" },
  { icon: "verified", label: "Management" },
];

export const HERO_GAMES: HeroGame[] = [
  {
    id: "bmi-hero",
    title: "Health Station",
    description: "Calculate BMI, track heart rate zones, and monitor physical endurance.",
    tag: "New",
    buttonText: "Open Tools",
    gradientClass: "from-emerald-500 to-teal-600",
    icon: "monitor_heart",
    textColorClass: "text-emerald-50",
    buttonTextColorClass: "text-emerald-700"
  },
  {
    id: "math-relay-hero",
    title: "Math Relay",
    description: "High-energy team math challenges. Race against the clock!",
    tag: "Active",
    buttonText: "Start Race",
    gradientClass: "from-blue-600 to-indigo-600",
    icon: "timer",
    textColorClass: "text-blue-50",
    buttonTextColorClass: "text-blue-700"
  },
  {
    id: "periodic-hero",
    title: "Element Hunt",
    description: "Master the periodic table with this fast-paced identification game.",
    tag: "Science",
    buttonText: "Play Now",
    gradientClass: "from-purple-600 to-pink-600",
    icon: "science",
    textColorClass: "text-purple-50",
    buttonTextColorClass: "text-purple-700"
  },
  {
    id: "quick-pick-hero",
    title: "Quick Pick",
    description: "The essential classroom tool for random student selection.",
    tag: "Essential",
    buttonText: "Pick Student",
    gradientClass: "from-cyan-500 to-blue-500",
    icon: "touch_app",
    textColorClass: "text-cyan-50",
    buttonTextColorClass: "text-cyan-700"
  }
];

export const GAMES: Game[] = [
  // --- Mathematics ---
  {
    id: "math-relay",
    title: "Math Relay",
    subtitle: "Team Race",
    description: "Teams solve a sequence of math problems; first to finish wins.",
    icon: "sprint",
    iconColorClass: "text-blue-600",
    gradientFrom: "from-blue-600/10",
    isPremium: false,
    category: "Mathematics",
    categoryColorClass: "bg-blue-600/10 text-blue-600 dark:text-blue-400",
    metaIcon: "group",
    metaText: "Teams"
  },
  {
    id: "number-hunt",
    title: "Number Hunt",
    subtitle: "Puzzle",
    description: "Find the target numbers hidden in a grid before time runs out.",
    icon: "grid_3x3",
    iconColorClass: "text-indigo-500",
    gradientFrom: "from-indigo-500/10",
    isPremium: false,
    category: "Mathematics",
    categoryColorClass: "bg-indigo-500/10 text-indigo-600 dark:text-indigo-400",
    metaIcon: "search",
    metaText: "Solo"
  },
  {
    id: "equation-builder",
    title: "Equation Builder",
    subtitle: "Logic",
    description: "Construct equations to reach the target number.",
    icon: "functions",
    iconColorClass: "text-cyan-600",
    gradientFrom: "from-cyan-600/10",
    isPremium: false,
    category: "Mathematics",
    categoryColorClass: "bg-cyan-600/10 text-cyan-600 dark:text-cyan-400",
    metaIcon: "drag_indicator",
    metaText: "Logic"
  },
  {
    id: "probability-quiz",
    title: "Probability",
    subtitle: "Math Quiz",
    description: "Test understanding of chance with coins and dice problems.",
    icon: "casino",
    iconColorClass: "text-violet-500",
    gradientFrom: "from-violet-500/10",
    isPremium: false,
    category: "Mathematics",
    categoryColorClass: "bg-violet-500/10 text-violet-600 dark:text-violet-400",
    metaIcon: "school",
    metaText: "Quiz"
  },

  // --- Science ---
  {
    id: "periodic-table",
    title: "Element Hunt",
    subtitle: "Chemistry",
    description: "Identify elements or symbols quickly in this periodic table game.",
    icon: "science",
    iconColorClass: "text-purple-600",
    gradientFrom: "from-purple-600/10",
    isPremium: false,
    category: "Science",
    categoryColorClass: "bg-purple-600/10 text-purple-600 dark:text-purple-400",
    metaIcon: "school",
    metaText: "Quiz"
  },
  {
    id: "lab-sim",
    title: "Lab Safety",
    subtitle: "Simulation",
    description: "Identify hazards and select correct equipment for experiments.",
    icon: "biotech",
    iconColorClass: "text-green-600",
    gradientFrom: "from-green-600/10",
    isPremium: false,
    category: "Science",
    categoryColorClass: "bg-green-600/10 text-green-600 dark:text-green-400",
    metaIcon: "warning",
    metaText: "Visual"
  },
  {
    id: "human-body",
    title: "Body Quiz",
    subtitle: "Biology",
    description: "Match organs to functions in this interactive anatomy quiz.",
    icon: "accessibility",
    iconColorClass: "text-red-500",
    gradientFrom: "from-red-500/10",
    isPremium: false,
    category: "Science",
    categoryColorClass: "bg-red-500/10 text-red-600 dark:text-red-400",
    metaIcon: "favorite",
    metaText: "Anatomy"
  },

  // --- Language ---
  {
    id: "word-builder",
    title: "Word Scramble",
    subtitle: "Vocabulary",
    description: "Unscramble letters to form words before time runs out.",
    icon: "spellcheck",
    iconColorClass: "text-yellow-600",
    gradientFrom: "from-yellow-600/10",
    isPremium: false,
    category: "Language",
    categoryColorClass: "bg-yellow-600/10 text-yellow-600 dark:text-yellow-400",
    metaIcon: "edit",
    metaText: "Vocab"
  },
  {
    id: "story-builder",
    title: "Story Prompt",
    subtitle: "Writing",
    description: "Generate creative writing prompts with genre, character, and setting.",
    icon: "auto_stories",
    iconColorClass: "text-pink-500",
    gradientFrom: "from-pink-500/10",
    isPremium: false,
    category: "Language",
    categoryColorClass: "bg-pink-500/10 text-pink-600 dark:text-pink-400",
    metaIcon: "edit_note",
    metaText: "Creative"
  },
  {
    id: "popcorn-reading",
    title: "Popcorn Read",
    subtitle: "Speaking",
    description: "Randomly select the next reader in a fun 'pop' style.",
    icon: "local_activity",
    iconColorClass: "text-amber-500",
    gradientFrom: "from-amber-500/10",
    isPremium: false,
    category: "Language",
    categoryColorClass: "bg-amber-500/10 text-amber-600 dark:text-amber-400",
    metaIcon: "record_voice_over",
    metaText: "Reading"
  },
  {
    id: "speed-debate",
    title: "Speed Debate",
    subtitle: "Speaking",
    description: "Generate random topics for quick 1-minute arguments.",
    icon: "record_voice_over",
    iconColorClass: "text-red-500",
    gradientFrom: "from-red-500/10",
    isPremium: false,
    category: "Language",
    categoryColorClass: "bg-red-500/10 text-red-600 dark:text-red-400",
    metaIcon: "timer",
    metaText: "Debate"
  },
  {
    id: "story-chain",
    title: "Story Chain",
    subtitle: "Collaborative",
    description: "Build a story together one sentence at a time.",
    icon: "menu_book",
    iconColorClass: "text-emerald-500",
    gradientFrom: "from-emerald-500/10",
    isPremium: false,
    category: "Language",
    categoryColorClass: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400",
    metaIcon: "group",
    metaText: "Class"
  },
  {
    id: "debate-duel",
    title: "Debate Duel",
    subtitle: "Versus",
    description: "Timed debate tool for two students or teams.",
    icon: "swords",
    iconColorClass: "text-orange-500",
    gradientFrom: "from-orange-500/10",
    isPremium: true,
    category: "Language",
    categoryColorClass: "bg-orange-500/10 text-orange-600 dark:text-orange-400",
    metaIcon: "people",
    metaText: "2 Players"
  },
  {
    id: "emoji-story",
    title: "Emoji Story",
    subtitle: "Creative",
    description: "Generate random emojis to inspire a creative story.",
    icon: "mood",
    iconColorClass: "text-yellow-500",
    gradientFrom: "from-yellow-500/10",
    isPremium: false,
    category: "Language",
    categoryColorClass: "bg-yellow-500/10 text-yellow-600 dark:text-yellow-400",
    metaIcon: "lightbulb",
    metaText: "Prompt"
  },

  // --- Social Studies ---
  {
    id: "map-quiz",
    title: "Map Master",
    subtitle: "Geography",
    description: "Identify continents and oceans in this geography challenge.",
    icon: "public",
    iconColorClass: "text-blue-500",
    gradientFrom: "from-blue-500/10",
    isPremium: false,
    category: "Social Studies",
    categoryColorClass: "bg-blue-500/10 text-blue-600 dark:text-blue-400",
    metaIcon: "map",
    metaText: "Geo"
  },
  {
    id: "timeline-challenge",
    title: "Time Line",
    subtitle: "History",
    description: "Place historical events in the correct chronological order.",
    icon: "history",
    iconColorClass: "text-amber-700",
    gradientFrom: "from-amber-700/10",
    isPremium: false,
    category: "Social Studies",
    categoryColorClass: "bg-amber-700/10 text-amber-700 dark:text-amber-500",
    metaIcon: "schedule",
    metaText: "History"
  },

  // --- Health & PE ---
  {
    id: "bmi-calc",
    title: "BMI Calc",
    subtitle: "Health Tool",
    description: "Calculate Body Mass Index and understand health categories.",
    icon: "monitor_weight",
    iconColorClass: "text-teal-500",
    gradientFrom: "from-teal-500/10",
    isPremium: false,
    category: "Health & PE",
    categoryColorClass: "bg-teal-500/10 text-teal-600 dark:text-teal-400",
    metaIcon: "health_and_safety",
    metaText: "Calc"
  },
  {
    id: "heart-rate",
    title: "Heart Zones",
    subtitle: "Fitness",
    description: "Input heart rate to determine fitness intensity zone.",
    icon: "ecg_heart",
    iconColorClass: "text-red-600",
    gradientFrom: "from-red-600/10",
    isPremium: false,
    category: "Health & PE",
    categoryColorClass: "bg-red-600/10 text-red-600 dark:text-red-400",
    metaIcon: "favorite",
    metaText: "Pulse"
  },
  {
    id: "pe-timer",
    title: "Interval Timer",
    subtitle: "Workout",
    description: "Customizable work/rest timer for circuit training.",
    icon: "timer",
    iconColorClass: "text-orange-500",
    gradientFrom: "from-orange-500/10",
    isPremium: false,
    category: "Health & PE",
    categoryColorClass: "bg-orange-500/10 text-orange-600 dark:text-orange-400",
    metaIcon: "fitness_center",
    metaText: "Active"
  },
  {
    id: "relay-challenge",
    title: "Relay Timer",
    subtitle: "Stopwatch",
    description: "Track lap times for relay races or stations.",
    icon: "directions_run",
    iconColorClass: "text-green-500",
    gradientFrom: "from-green-500/10",
    isPremium: false,
    category: "Health & PE",
    categoryColorClass: "bg-green-500/10 text-green-600 dark:text-green-400",
    metaIcon: "timer",
    metaText: "Sport"
  },

  // --- Wellness ---
  {
    id: "zen-forest",
    title: "Zen Forest",
    subtitle: "Mindfulness",
    description: "Guided breathing visualization for focus and calm.",
    icon: "self_improvement",
    iconColorClass: "text-indigo-500",
    gradientFrom: "from-indigo-500/10",
    isPremium: false,
    category: "Wellness",
    categoryColorClass: "bg-indigo-500/10 text-indigo-600 dark:text-indigo-400",
    metaIcon: "spa",
    metaText: "Relax"
  },
  {
    id: "mindful-breathing",
    title: "4-7-8 Breath",
    subtitle: "Technique",
    description: "Scientific breathing pattern to reduce anxiety.",
    icon: "air",
    iconColorClass: "text-cyan-500",
    gradientFrom: "from-cyan-500/10",
    isPremium: false,
    category: "Wellness",
    categoryColorClass: "bg-cyan-500/10 text-cyan-600 dark:text-cyan-400",
    metaIcon: "lungs",
    metaText: "Focus"
  },
  {
    id: "stretch-move",
    title: "Stretch & Move",
    subtitle: "Activity",
    description: "Guided stretches for brain breaks.",
    icon: "accessibility_new",
    iconColorClass: "text-green-500",
    gradientFrom: "from-green-500/10",
    isPremium: false,
    category: "Wellness",
    categoryColorClass: "bg-green-500/10 text-green-600 dark:text-green-400",
    metaIcon: "directions_run",
    metaText: "Active"
  },
  {
    id: "quick-dance",
    title: "Dance Break",
    subtitle: "Energy",
    description: "60-second music visualization for getting energy out.",
    icon: "music_note",
    iconColorClass: "text-pink-500",
    gradientFrom: "from-pink-500/10",
    isPremium: false,
    category: "Wellness",
    categoryColorClass: "bg-pink-500/10 text-pink-600 dark:text-pink-400",
    metaIcon: "music_note",
    metaText: "Active"
  },
  {
    id: "hot-potato",
    title: "Hot Potato",
    subtitle: "Fun",
    description: "Pass the item before the timer explodes!",
    icon: "local_fire_department",
    iconColorClass: "text-orange-500",
    gradientFrom: "from-orange-500/10",
    isPremium: false,
    category: "Wellness",
    categoryColorClass: "bg-orange-500/10 text-orange-600 dark:text-orange-400",
    metaIcon: "timer",
    metaText: "Game"
  },
  {
    id: "reaction-challenge",
    title: "Reaction Test",
    subtitle: "Reflexes",
    description: "Test student reaction times. Good for brain activation.",
    icon: "bolt",
    iconColorClass: "text-yellow-500",
    gradientFrom: "from-yellow-500/10",
    isPremium: false,
    category: "Wellness",
    categoryColorClass: "bg-yellow-500/10 text-yellow-600 dark:text-yellow-400",
    metaIcon: "speed",
    metaText: "Solo"
  },

  // --- Decision ---
  {
    id: "dice-roll",
    title: "Dice Roll",
    subtitle: "Physics Dice",
    description: "Simulates physical dice with animations.",
    icon: "casino",
    iconColorClass: "text-purple-500",
    gradientFrom: "from-purple-500/10",
    isPremium: false,
    category: "Decision",
    categoryColorClass: "bg-purple-500/10 text-purple-600 dark:text-purple-400",
    metaIcon: "casino",
    metaText: "Random"
  },
  {
    id: "coin-flip",
    title: "Coin Flip",
    subtitle: "Heads/Tails",
    description: "Quick random decision maker.",
    icon: "monetization_on",
    iconColorClass: "text-amber-500",
    gradientFrom: "from-amber-500/10",
    isPremium: false,
    category: "Decision",
    categoryColorClass: "bg-amber-500/10 text-amber-600 dark:text-amber-400",
    metaIcon: "cached",
    metaText: "Instant"
  },
  {
    id: "wheel-spin",
    title: "Wheel Spin",
    subtitle: "Spinner",
    description: "Customizable wheel for prizes or names.",
    icon: "data_usage",
    iconColorClass: "text-pink-500",
    gradientFrom: "from-pink-500/10",
    isPremium: true,
    category: "Decision",
    categoryColorClass: "bg-pink-500/10 text-pink-600 dark:text-pink-400",
    metaIcon: "rotate_right",
    metaText: "Random"
  },
  {
    id: "pebble-toss",
    title: "Pebble Toss",
    subtitle: "Yes/No",
    description: "Toss a pebble into the pond to get a random answer.",
    icon: "water_drop",
    iconColorClass: "text-cyan-500",
    gradientFrom: "from-cyan-500/10",
    isPremium: false,
    category: "Decision",
    categoryColorClass: "bg-cyan-500/10 text-cyan-600 dark:text-cyan-400",
    metaIcon: "waves",
    metaText: "Yes/No"
  },
  {
    id: "mystery-box",
    title: "Mystery Box",
    subtitle: "Rewards",
    description: "Open a box for a random classroom reward.",
    icon: "inventory_2",
    iconColorClass: "text-indigo-500",
    gradientFrom: "from-indigo-500/10",
    isPremium: false,
    category: "Decision",
    categoryColorClass: "bg-indigo-500/10 text-indigo-600 dark:text-indigo-400",
    metaIcon: "card_giftcard",
    metaText: "Prize"
  },

  // --- Group Activities ---
  {
    id: "team-maker",
    title: "Team Maker",
    subtitle: "Grouper",
    description: "Instantly creates balanced groups.",
    icon: "diversity_3",
    iconColorClass: "text-green-500",
    gradientFrom: "from-green-500/10",
    isPremium: true,
    category: "Group Activities",
    categoryColorClass: "bg-green-500/10 text-green-600 dark:text-green-400",
    metaIcon: "group",
    metaText: "Teams"
  },
  {
    id: "think-pair-share",
    title: "Pair Up",
    subtitle: "Discussion",
    description: "Randomly pair students for discussion.",
    icon: "people_alt",
    iconColorClass: "text-cyan-500",
    gradientFrom: "from-cyan-500/10",
    isPremium: false,
    category: "Group Activities",
    categoryColorClass: "bg-cyan-500/10 text-cyan-600 dark:text-cyan-400",
    metaIcon: "group",
    metaText: "Pairs"
  },
  {
    id: "icebreaker-roulette",
    title: "Icebreaker",
    subtitle: "Questions",
    description: "Random questions to get students talking.",
    icon: "question_answer",
    iconColorClass: "text-teal-500",
    gradientFrom: "from-teal-500/10",
    isPremium: false,
    category: "Group Activities",
    categoryColorClass: "bg-teal-500/10 text-teal-600 dark:text-teal-400",
    metaIcon: "chat",
    metaText: "Class"
  },
  {
    id: "two-truths-lie",
    title: "2 Truths 1 Lie",
    subtitle: "Social",
    description: "Classic get-to-know-you game.",
    icon: "fact_check",
    iconColorClass: "text-purple-500",
    gradientFrom: "from-purple-500/10",
    isPremium: false,
    category: "Group Activities",
    categoryColorClass: "bg-purple-500/10 text-purple-600 dark:text-purple-400",
    metaIcon: "psychology",
    metaText: "Game"
  },
  {
    id: "human-bingo",
    title: "Human Bingo",
    subtitle: "Mixer",
    description: "Generate a bingo card of traits for students to find.",
    icon: "grid_on",
    iconColorClass: "text-blue-600",
    gradientFrom: "from-blue-600/10",
    isPremium: false,
    category: "Group Activities",
    categoryColorClass: "bg-blue-600/10 text-blue-600 dark:text-blue-400",
    metaIcon: "search",
    metaText: "Mixer"
  },
  {
    id: "collaborative-puzzle",
    title: "Vault Unlock",
    subtitle: "Co-op",
    description: "Class works together to fill the progress bar.",
    icon: "lock_open",
    iconColorClass: "text-amber-500",
    gradientFrom: "from-amber-500/10",
    isPremium: false,
    category: "Group Activities",
    categoryColorClass: "bg-amber-500/10 text-amber-600 dark:text-amber-400",
    metaIcon: "handshake",
    metaText: "Co-op"
  },
  {
    id: "peer-quiz",
    title: "Peer Quiz",
    subtitle: "Review",
    description: "Display student-generated questions for the class.",
    icon: "quiz",
    iconColorClass: "text-indigo-500",
    gradientFrom: "from-indigo-500/10",
    isPremium: false,
    category: "Group Activities",
    categoryColorClass: "bg-indigo-500/10 text-indigo-600 dark:text-indigo-400",
    metaIcon: "school",
    metaText: "Review"
  },

  // --- Management ---
  {
    id: "quick-pick",
    title: "Quick Pick",
    subtitle: "Random Student",
    description: "Selects a single student randomly.",
    icon: "touch_app",
    iconColorClass: "text-blue-500",
    gradientFrom: "from-blue-500/10",
    isPremium: false,
    category: "Management",
    categoryColorClass: "bg-blue-500/10 text-blue-600 dark:text-blue-400",
    metaIcon: "person",
    metaText: "1 Player"
  },
  {
    id: "class-timer",
    title: "Class Timer",
    subtitle: "Countdown",
    description: "Focused countdown timer for activities.",
    icon: "timer",
    iconColorClass: "text-red-500",
    gradientFrom: "from-red-500/10",
    isPremium: false,
    category: "Management",
    categoryColorClass: "bg-red-500/10 text-red-600 dark:text-red-400",
    metaIcon: "schedule",
    metaText: "Time"
  },
  {
    id: "stopwatch",
    title: "Stopwatch",
    subtitle: "Timer",
    description: "Track elapsed time with laps.",
    icon: "timer_10",
    iconColorClass: "text-slate-600",
    gradientFrom: "from-slate-500/10",
    isPremium: false,
    category: "Management",
    categoryColorClass: "bg-slate-500/10 text-slate-600 dark:text-slate-400",
    metaIcon: "history",
    metaText: "Time"
  },
  {
    id: "noise-level",
    title: "Voice Boost",
    subtitle: "Monitor",
    description: "Visual noise meter to manage classroom volume.",
    icon: "graphic_eq",
    iconColorClass: "text-indigo-500",
    gradientFrom: "from-indigo-500/10",
    isPremium: false,
    category: "Management",
    categoryColorClass: "bg-indigo-500/10 text-indigo-600 dark:text-indigo-400",
    metaIcon: "volume_up",
    metaText: "Mic"
  },
  {
    id: "poll-maker",
    title: "Quick Poll",
    subtitle: "Voting",
    description: "Instant class voting visualization.",
    icon: "poll",
    iconColorClass: "text-indigo-500",
    gradientFrom: "from-indigo-500/10",
    isPremium: false,
    category: "Management",
    categoryColorClass: "bg-indigo-500/10 text-indigo-600 dark:text-indigo-400",
    metaIcon: "bar_chart",
    metaText: "Vote"
  },
  {
    id: "turn-order",
    title: "Turn Order",
    subtitle: "Sequence",
    description: "Generate a random order for presentations.",
    icon: "format_list_numbered",
    iconColorClass: "text-teal-600",
    gradientFrom: "from-teal-600/10",
    isPremium: false,
    category: "Management",
    categoryColorClass: "bg-teal-600/10 text-teal-600 dark:text-teal-400",
    metaIcon: "list",
    metaText: "List"
  },
  {
    id: "traffic-light",
    title: "Traffic Light",
    subtitle: "Status",
    description: "Visual signal for class activity status.",
    icon: "traffic",
    iconColorClass: "text-yellow-600",
    gradientFrom: "from-yellow-600/10",
    isPremium: false,
    category: "Management",
    categoryColorClass: "bg-yellow-600/10 text-yellow-600 dark:text-yellow-400",
    metaIcon: "visibility",
    metaText: "Signal"
  },
  {
    id: "scoreboard",
    title: "Scoreboard",
    subtitle: "Tracker",
    description: "Keep score for multiple teams.",
    icon: "scoreboard",
    iconColorClass: "text-blue-700",
    gradientFrom: "from-blue-700/10",
    isPremium: false,
    category: "Management",
    categoryColorClass: "bg-blue-700/10 text-blue-700 dark:text-blue-400",
    metaIcon: "numbers",
    metaText: "Points"
  },
  {
    id: "skill-spinner",
    title: "Task Assign",
    subtitle: "Random",
    description: "Assign a random student to a random task.",
    icon: "assignment_ind",
    iconColorClass: "text-purple-600",
    gradientFrom: "from-purple-600/10",
    isPremium: false,
    category: "Management",
    categoryColorClass: "bg-purple-600/10 text-purple-600 dark:text-purple-400",
    metaIcon: "task",
    metaText: "Assign"
  },
  {
    id: "question-bag",
    title: "Question Bag",
    subtitle: "Picker",
    description: "Digital hat for drawing random questions.",
    icon: "shopping_bag",
    iconColorClass: "text-amber-600",
    gradientFrom: "from-amber-600/10",
    isPremium: false,
    category: "Management",
    categoryColorClass: "bg-amber-600/10 text-amber-600 dark:text-amber-400",
    metaIcon: "help",
    metaText: "Draw"
  },
  {
    id: "focus-tracker",
    title: "Focus Time",
    subtitle: "Tracker",
    description: "Track accumulated focus time.",
    icon: "hourglass_top",
    iconColorClass: "text-blue-500",
    gradientFrom: "from-blue-500/10",
    isPremium: false,
    category: "Management",
    categoryColorClass: "bg-blue-500/10 text-blue-600 dark:text-blue-400",
    metaIcon: "timelapse",
    metaText: "Time"
  },
  {
    id: "participation-points",
    title: "Points",
    subtitle: "Rewards",
    description: "Simple star tracker for student participation.",
    icon: "star",
    iconColorClass: "text-yellow-500",
    gradientFrom: "from-yellow-500/10",
    isPremium: false,
    category: "Management",
    categoryColorClass: "bg-yellow-500/10 text-yellow-600 dark:text-yellow-400",
    metaIcon: "emoji_events",
    metaText: "Track"
  },
  {
    id: "behavior-bingo",
    title: "Goal Bingo",
    subtitle: "Behavior",
    description: "Track class goals with a bingo board.",
    icon: "checklist",
    iconColorClass: "text-green-600",
    gradientFrom: "from-green-600/10",
    isPremium: false,
    category: "Management",
    categoryColorClass: "bg-green-600/10 text-green-600 dark:text-green-400",
    metaIcon: "check_circle",
    metaText: "Goals"
  },
  {
    id: "virtual-badge",
    title: "Badges",
    subtitle: "Awards",
    description: "Display virtual awards for good behavior.",
    icon: "military_tech",
    iconColorClass: "text-orange-500",
    gradientFrom: "from-orange-500/10",
    isPremium: false,
    category: "Management",
    categoryColorClass: "bg-orange-500/10 text-orange-600 dark:text-orange-400",
    metaIcon: "badge",
    metaText: "Award"
  },
  {
    id: "quick-quiz",
    title: "Quick Quiz",
    subtitle: "Assessment",
    description: "Simple A/B/C/D visualizer for verbal quizzes.",
    icon: "quiz",
    iconColorClass: "text-indigo-600",
    gradientFrom: "from-indigo-600/10",
    isPremium: false,
    category: "Management",
    categoryColorClass: "bg-indigo-600/10 text-indigo-600 dark:text-indigo-400",
    metaIcon: "check",
    metaText: "Quiz"
  },
  {
    id: "rank-vote",
    title: "Rank Vote",
    subtitle: "Voting",
    description: "Rank items based on class votes.",
    icon: "sort",
    iconColorClass: "text-blue-500",
    gradientFrom: "from-blue-500/10",
    isPremium: false,
    category: "Management",
    categoryColorClass: "bg-blue-500/10 text-blue-600 dark:text-blue-400",
    metaIcon: "list",
    metaText: "Vote"
  },
  {
    id: "reflection-cards",
    title: "Reflect",
    subtitle: "Review",
    description: "Random reflection prompts for end of lesson.",
    icon: "psychology_alt",
    iconColorClass: "text-purple-500",
    gradientFrom: "from-purple-500/10",
    isPremium: false,
    category: "Management",
    categoryColorClass: "bg-purple-500/10 text-purple-600 dark:text-purple-400",
    metaIcon: "chat_bubble",
    metaText: "Review"
  },
  {
    id: "exit-ticket",
    title: "Exit Ticket",
    subtitle: "Assessment",
    description: "Randomly select students for exit questions.",
    icon: "outbox",
    iconColorClass: "text-emerald-600",
    gradientFrom: "from-emerald-600/10",
    isPremium: true,
    category: "Management",
    categoryColorClass: "bg-emerald-600/10 text-emerald-600 dark:text-emerald-400",
    metaIcon: "check_box",
    metaText: "Ticket"
  }
];
